### ISSUE TITLE
Cant find panasonic_eolia integration

### ISSUE THREAD

**Issue by helfm** [avolmensky/panasonic_eolia#2]
Hi all,

Can someone help me.

I have installed the panasonic_eolia via hacs in my hassio, but I can not find the integration in the System.

Any idea whats running wrong?

KR Markus

**Comment by avolmensky** [comment]
@helfm You need configure it by editing configuration.yml. More information in https://github.com/avolmensky/panasonic_eolia/blob/main/README.md

**Comment by helfm** [comment]
Hi Andre,

Sorry, I forgot to mention that I also did the configuration in configuration.yaml.

Where else could be the problem?

KR Markus

**Comment by avolmensky** [comment]
Is there anything in the logs? Settings -> System -> Logs, look for panasonic_eolia.

**Comment by helfm** [comment]
Good morning Andre,

I found following log entry:

```
Logger: homeassistant.components.climate
Source: custom_components/panasonic_eolia/climate.py:65
Integration: Klima ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 07:55:03 (1 occurrences)
Last logged: 07:55:03

Error while setting up panasonic_eolia platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/panasonic_eolia/climate.py", line 65, in setup_platform
    api.login()
  File "/usr/local/lib/python3.10/site-packages/panasoniceolia/session.py", line 110, in login
    raise ResponseError(response.status_code, response.text)
panasoniceolia.session.ResponseError: Invalid response, status code: 400 - Data: {"code":"E-21291-00002","message":"サーバー時間とお手持ちの端末時間の時差が5分以上あります。お手持ちの端末の設定時間を確認してください。"}
```
KR Markus

**Comment by avolmensky** [comment]
Looks like it has something to do with your time being more than 5 minutes off the server time?

Just confirming you are trying to use a Panasonic Eolia AC? 

Are both you and the AC located in Japan?

**Comment by helfm** [comment]
Hi Andre,

I also had these Japanese characters translated, and was a bit puzzled about the content.

No, I am not in Japan, but live in Austria (Europe).

I control my air conditioning via the "Panasonic Comfort Cloud", and would like to control this air conditioning also via my Hassio. Concretely, I am only interested in the possibility to switch the air conditioner on or off with an automation via Hassio.

Have I perhaps misunderstood the description of this integration? I thought that it was the connection to this "Panasonic Comfort Cloud".

KR Markus

**Comment by avolmensky** [comment]
@helfm There is a Panasonic Comfort Cloud HACS plugin that you can use. This plugin is only for Panasonic Eolia devices (I don't think they exist outside of Japan)

**Comment by helfm** [comment]
Hi Andre,

Many thx for your support.

KR Markus
